import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case zhHans
    case en
    case ja

    var id: String { rawValue }

    var title: String {
        switch self {
        case .zhHans: return "中文"
        case .en: return "English"
        case .ja: return "日本語"
        }
    }

    func text(_ key: String) -> String {
        guard self != .zhHans else { return key }
        return Self.translations[rawValue]?[key] ?? key
    }

    private static let translations: [String: [String: String]] = [
        "en": [
            "候物": "AwaitGoods",
            "设置": "Settings",
            "想买": "Wanted",
            "已拥有": "Owned",
            "放下": "Let Go",
            "全部": "All",
            "搜索名称、备注或分类": "Search name, note, or category",
            "排序": "Sort",
            "批量": "Batch",
            "整理清单": "Organize",
            "完成整理": "Done Organizing",
            "先记下心动，给预算一点空间": "Save the wish first. Give the budget room.",
            "清单很轻，今天也很清爽": "The list is light today.",
            "还有 %d 件想买的东西": "%d wanted items",
            "暂无候物": "No wishes yet",
            "慢慢存，轻轻买": "Save slowly, buy lightly",
            "先记下一个心愿": "Save a wish first",
            "价格": "Price",
            "已存": "Saved",
            "标签": "Tag",
            "价格需大于 0": "Price must be greater than 0",
            "已存需大于 0": "Saved amount must be greater than 0",
            "已存不能超过价格": "Saved amount cannot exceed price",
            "已选 %d 件": "%d selected",
            "轻点左侧图标多选": "Tap the left icon to select",
            "可以批量放下、删除或换标记": "Let go, delete, or mark in batch",
            "完成": "Done",
            "删除": "Delete",
            "标记": "Mark",
            "删除后不可恢复": "This cannot be undone",
            "删除选中的候物？": "Delete selected wishes?",
            "取消": "Cancel",
            "手动排序": "Manual",
            "最近添加": "Recent",
            "存钱进度": "Savings",
            "价格高低": "Price",
            "优先级": "Priority",
            "换个标记": "Change mark",
            "编辑": "Edit",
            "复制链接": "Copy link",
            "数码": "Digital",
            "衣物": "Clothing",
            "家居": "Home",
            "书影音": "Books",
            "礼物": "Gift",
            "运动": "Sports",
            "语言": "Language",
            "日常偏好": "Preferences",
            "默认值轻一点，记录就不会有负担": "Keep defaults light so logging stays easy",
            "数据": "Data",
            "留一份记录，也可以随时清空": "Keep a copy or clear everything anytime",
            "外观模式": "Appearance",
            "小组件展示": "Widget Display",
            "小号 1 件 · 中号 3 件 · 大号 5 件": "Small 1 · Medium 3 · Large 5",
            "生成导出文件": "Create Export File",
            "保存为 JSON 备份": "Save a JSON backup",
            "分享导出文件": "Share Export File",
            "文件已生成，可以发送或存到 iCloud": "File created. Send it or save to iCloud.",
            "清空全部数据": "Clear All Data",
            "会删除所有候物和存钱记录": "Deletes every wish and savings record",
            "联系客服": "Contact Support",
            "有任何问题或建议，欢迎联系我们。": "Questions or ideas are welcome.",
            "微信": "WeChat",
            "已复制": "Copied",
            "点击复制": "Tap to copy",
            "关于 App": "About App",
            "候物 AwaitGoods": "AwaitGoods",
            "v1.0 · 慢慢存，轻轻买": "v1.0 · Save slowly, buy lightly",
            "所有候物都会被删除": "All wishes will be deleted",
            "清空": "Clear",
            "跟随系统": "System",
            "浅色": "Light",
            "深色": "Dark",
            "现在怎么处理": "Next Step",
            "详情": "Details",
            "返回": "Back",
            "存钱": "Savings",
            "目标": "Target",
            "还差": "Left",
            "目标未定": "No target yet",
            "已存满": "Fully saved",
            "记录": "Notes",
            "打开商品页面": "Open Product Page",
            "存入金额": "Deposit amount",
            "存入": "Add",
            "补满": "Fill",
            "已经存满，不需要继续存入": "Already fully saved",
            "存入金额需大于 0": "Deposit must be greater than 0",
            "本次存入不能超过还差金额": "Deposit cannot exceed remaining amount",
            "一点点存起来，心愿会变得更踏实。": "Saving bit by bit makes the wish feel real.",
            "已经拥有，记得回看它是否真的被使用。": "Owned now. Remember to see if it is actually used.",
            "放下也很好，清单因此更轻。": "Letting go is good too. The list gets lighter.",
            "先留在清单里，让预算慢慢清楚。": "Keep it here while the budget gets clearer.",
            "想买什么": "What do you want?",
            "先把心动记下来，预算可以慢慢补": "Save the spark first. The budget can follow.",
            "名称": "Name",
            "比如 AirPods、通勤包": "e.g. AirPods, commute bag",
            "可选": "Optional",
            "分类": "Category",
            "链接": "Link",
            "商品链接，可选": "Product link, optional",
            "存钱计划": "Savings Plan",
            "看见一点点靠近，比倒计时更舒服": "Progress feels better than a countdown",
            "标记与备注": "Mark & Note",
            "为什么想买？现在担心什么？": "Why want it? Any concern now?",
            "新候物": "New Wish",
            "保存": "Save",
            "先放进清单": "Put it on the list",
            "调整这件候物": "Edit this wish",
            "少填几项也没关系，清单会安静地接住它。": "A few fields are enough. The list will hold it.",
            "标记色": "Mark Color",
            "低": "Low",
            "中": "Medium",
            "高": "High",
            "无": "None",
            "绿色": "Green",
            "黄色": "Yellow",
            "粉色": "Pink",
            "灰色": "Gray"
        ],
        "ja": [
            "候物": "候物",
            "设置": "設定",
            "想买": "欲しい",
            "已拥有": "所有済み",
            "放下": "手放す",
            "全部": "すべて",
            "搜索名称、备注或分类": "名前、メモ、カテゴリを検索",
            "排序": "並び替え",
            "批量": "一括",
            "整理清单": "リスト整理",
            "完成整理": "整理を完了",
            "先记下心动，给预算一点空间": "まず気持ちを残して、予算に余白を。",
            "清单很轻，今天也很清爽": "リストは軽く、今日もすっきり。",
            "还有 %d 件想买的东西": "欲しいものが %d 件あります",
            "暂无候物": "まだ候物はありません",
            "慢慢存，轻轻买": "少しずつ貯めて、軽やかに買う",
            "先记下一个心愿": "まずひとつ残す",
            "价格": "価格",
            "已存": "貯金済み",
            "标签": "タグ",
            "价格需大于 0": "価格は 0 より大きくしてください",
            "已存需大于 0": "貯金額は 0 より大きくしてください",
            "已存不能超过价格": "貯金額は価格を超えられません",
            "已选 %d 件": "%d 件選択中",
            "轻点左侧图标多选": "左のアイコンで複数選択",
            "可以批量放下、删除或换标记": "一括で手放す・削除・印を変更",
            "完成": "完了",
            "删除": "削除",
            "标记": "印",
            "删除后不可恢复": "削除すると元に戻せません",
            "删除选中的候物？": "選択した候物を削除しますか？",
            "取消": "キャンセル",
            "手动排序": "手動順",
            "最近添加": "最近追加",
            "存钱进度": "貯金進捗",
            "价格高低": "価格順",
            "优先级": "優先度",
            "换个标记": "印を変える",
            "编辑": "編集",
            "复制链接": "リンクをコピー",
            "数码": "デジタル",
            "衣物": "服",
            "家居": "暮らし",
            "书影音": "本・映像",
            "礼物": "ギフト",
            "运动": "スポーツ",
            "语言": "言語",
            "日常偏好": "日常設定",
            "默认值轻一点，记录就不会有负担": "軽い初期設定で、記録を負担なく",
            "数据": "データ",
            "留一份记录，也可以随时清空": "記録を残して、いつでも整理できます",
            "外观模式": "外観モード",
            "小组件展示": "ウィジェット表示",
            "小号 1 件 · 中号 3 件 · 大号 5 件": "小 1 件・中 3 件・大 5 件",
            "生成导出文件": "書き出しファイルを作成",
            "保存为 JSON 备份": "JSON バックアップとして保存",
            "分享导出文件": "書き出しファイルを共有",
            "文件已生成，可以发送或存到 iCloud": "ファイルを作成しました。送信または iCloud に保存できます。",
            "清空全部数据": "すべてのデータを削除",
            "会删除所有候物和存钱记录": "すべての候物と貯金記録を削除します",
            "联系客服": "サポートに連絡",
            "有任何问题或建议，欢迎联系我们。": "質問や提案があればご連絡ください。",
            "微信": "WeChat",
            "已复制": "コピー済み",
            "点击复制": "タップしてコピー",
            "关于 App": "アプリについて",
            "候物 AwaitGoods": "候物 AwaitGoods",
            "v1.0 · 慢慢存，轻轻买": "v1.0・少しずつ貯めて、軽やかに買う",
            "所有候物都会被删除": "すべての候物が削除されます",
            "清空": "削除",
            "跟随系统": "システム",
            "浅色": "ライト",
            "深色": "ダーク",
            "现在怎么处理": "次にどうする？",
            "详情": "詳細",
            "返回": "戻る",
            "存钱": "貯金",
            "目标": "目標",
            "还差": "残り",
            "目标未定": "目標未設定",
            "已存满": "貯まりました",
            "记录": "記録",
            "打开商品页面": "商品ページを開く",
            "存入金额": "貯金額を入力",
            "存入": "追加",
            "补满": "満額にする",
            "已经存满，不需要继续存入": "すでに満額です",
            "存入金额需大于 0": "追加額は 0 より大きくしてください",
            "本次存入不能超过还差金额": "追加額は残額を超えられません",
            "一点点存起来，心愿会变得更踏实。": "少しずつ貯めると、願いが現実に近づきます。",
            "已经拥有，记得回看它是否真的被使用。": "所有済み。ちゃんと使えているか振り返りましょう。",
            "放下也很好，清单因此更轻。": "手放すのも良い選択。リストが軽くなります。",
            "先留在清单里，让预算慢慢清楚。": "まずリストに置いて、予算をゆっくり見極めましょう。",
            "想买什么": "何が欲しい？",
            "先把心动记下来，预算可以慢慢补": "ときめきを先に残して、予算は少しずつ",
            "名称": "名前",
            "比如 AirPods、通勤包": "例：AirPods、通勤バッグ",
            "可选": "任意",
            "分类": "カテゴリ",
            "链接": "リンク",
            "商品链接，可选": "商品リンク（任意）",
            "存钱计划": "貯金プラン",
            "看见一点点靠近，比倒计时更舒服": "カウントダウンより、近づく感覚を",
            "标记与备注": "印とメモ",
            "为什么想买？现在担心什么？": "なぜ欲しい？今の気がかりは？",
            "新候物": "新しい候物",
            "保存": "保存",
            "先放进清单": "まずリストへ",
            "调整这件候物": "この候物を編集",
            "少填几项也没关系，清单会安静地接住它。": "少しだけでも大丈夫。リストが静かに受け止めます。",
            "标记色": "印の色",
            "低": "低",
            "中": "中",
            "高": "高",
            "无": "なし",
            "绿色": "緑",
            "黄色": "黄",
            "粉色": "ピンク",
            "灰色": "グレー"
        ]
    ]
}

private struct AppLanguageKey: EnvironmentKey {
    static let defaultValue: AppLanguage = .zhHans
}

extension EnvironmentValues {
    var appLanguage: AppLanguage {
        get { self[AppLanguageKey.self] }
        set { self[AppLanguageKey.self] = newValue }
    }
}
