import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case zhHans
    case zhHant
    case en
    case ja
    case fr
    case de
    case it
    case ko

    var id: String { rawValue }

    var title: String {
        switch self {
        case .zhHans: return "简体中文"
        case .zhHant: return "繁體中文"
        case .en: return "English"
        case .ja: return "日本語"
        case .fr: return "Français"
        case .de: return "Deutsch"
        case .it: return "Italiano"
        case .ko: return "한국어"
        }
    }

    func text(_ key: String) -> String {
        guard self != .zhHans else { return key }
        if let translation = Self.translations[rawValue]?[key] {
            return translation
        }
        return Self.translations[AppLanguage.en.rawValue]?[key] ?? key
    }

    private static let translations: [String: [String: String]] = [
        "zhHant": [
            "设置": "設定",
            "想买": "想買",
            "已拥有": "已擁有",
            "搜索名称、备注或分类": "搜尋名稱、備註或分類",
            "整理清单": "整理清單",
            "先记下心动，给预算一点空间": "先記下心動，給預算一點空間",
            "清单很轻，今天也很清爽": "清單很輕，今天也很清爽",
            "还有 %d 件想买的东西": "還有 %d 件想買的東西",
            "暂无候物": "暫無候物",
            "慢慢存，轻轻买": "慢慢存，輕輕買",
            "先记下一个心愿": "先記下一個心願",
            "价格": "價格",
            "标签": "標籤",
            "价格需大于 0": "價格需大於 0",
            "已存需大于 0": "已存需大於 0",
            "已存不能超过价格": "已存不能超過價格",
            "已选 %d 件": "已選 %d 件",
            "轻点左侧图标多选": "輕點左側圖示多選",
            "可以批量放下、删除或换标记": "可以批量放下、刪除或換標記",
            "可以批量放下、移入回收站或换标记": "可以批量放下、移入回收站或換標記",
            "删除": "刪除",
            "标记": "標記",
            "删除后不可恢复": "刪除後不可恢復",
            "移入回收站": "移入回收站",
            "移入回收站？": "移入回收站？",
            "删除会先放进回收站": "刪除會先放進回收站",
            "回收站": "回收站",
            "回收站为空": "回收站為空",
            "暂无已删除候物": "暫無已刪除候物",
            "恢复": "恢復",
            "彻底删除": "徹底刪除",
            "清空回收站？": "清空回收站？",
            "确认彻底删除？": "確認徹底刪除？",
            "这些候物将无法恢复": "這些候物將無法恢復",
            "已放入回收站": "已放入回收站",
            "已恢复": "已恢復",
            "删除选中的候物？": "刪除選中的候物？",
            "手动排序": "手動排序",
            "存钱进度": "存錢進度",
            "价格高低": "價格高低",
            "优先级": "優先級",
            "换个标记": "換個標記",
            "编辑": "編輯",
            "复制链接": "複製連結",
            "数码": "數碼",
            "书影音": "書影音",
            "礼物": "禮物",
            "运动": "運動",
            "语言": "語言",
            "轻触切换语言": "輕觸切換語言",
            "默认值轻一点，记录就不会有负担": "預設值輕一點，記錄就不會有負擔",
            "数据": "資料",
            "留一份记录，也可以随时清空": "留一份記錄，也可以隨時清空",
            "外观模式": "外觀模式",
            "主题配色": "主題配色",
            "春日纸笺": "春日紙箋",
            "清爽绿意与纸张质感": "清爽綠意與紙張質感",
            "海盐蓝调": "海鹽藍調",
            "蓝绿底色配一点珊瑚": "藍綠底色配一點珊瑚",
            "暮莓花园": "暮莓花園",
            "莓果、鼠尾草和纸白": "莓果、鼠尾草和紙白",
            "墨绿静夜": "墨綠靜夜",
            "深绿与温润木色": "深綠與溫潤木色",
            "杏茶暖光": "杏茶暖光",
            "杏色、茶棕和蓝灰": "杏色、茶棕和藍灰",
            "小组件展示": "小工具顯示",
            "小号 1 件 · 中号 3 件 · 大号 5 件": "小號 1 件 · 中號 3 件 · 大號 5 件",
            "导入备份文件": "匯入備份檔案",
            "从 JSON 恢复或合并候物": "從 JSON 恢復或合併候物",
            "生成导出文件": "生成匯出檔案",
            "保存为 JSON 备份": "儲存為 JSON 備份",
            "分享导出文件": "分享匯出檔案",
            "文件已生成，可以发送或存到 iCloud": "檔案已生成，可以傳送或存到 iCloud",
            "备份文件已导入": "備份檔案已匯入",
            "新增 %d 条 · 更新 %d 条": "新增 %d 筆 · 更新 %d 筆",
            "无法导入备份文件": "無法匯入備份檔案",
            "请确认选择的是候物导出的 JSON 文件": "請確認選擇的是候物匯出的 JSON 檔案",
            "备份文件里没有可导入的候物": "備份檔案裡沒有可匯入的候物",
            "清空全部数据": "清空全部資料",
            "会删除所有候物和存钱记录": "會刪除所有候物和存錢記錄",
            "联系客服": "聯絡客服",
            "有任何问题或建议，欢迎联系我们。": "有任何問題或建議，歡迎聯絡我們。",
            "已复制": "已複製",
            "点击复制": "點擊複製",
            "关于 App": "關於 App",
            "v1.0 · 慢慢存，轻轻买": "v1.0 · 慢慢存，輕輕買",
            "所有候物都会被删除": "所有候物都會被刪除",
            "跟随系统": "跟隨系統",
            "浅色": "淺色",
            "现在怎么处理": "現在怎麼處理",
            "详情": "詳情",
            "存钱": "存錢",
            "目标": "目標",
            "还差": "還差",
            "目标未定": "目標未定",
            "已存满": "已存滿",
            "记录": "記錄",
            "打开商品页面": "打開商品頁面",
            "存入金额": "存入金額",
            "补满": "補滿",
            "已经存满，不需要继续存入": "已經存滿，不需要繼續存入",
            "存入金额需大于 0": "存入金額需大於 0",
            "本次存入不能超过还差金额": "本次存入不能超過還差金額",
            "一点点存起来，心愿会变得更踏实。": "一點點存起來，心願會變得更踏實。",
            "已经拥有，记得回看它是否真的被使用。": "已經擁有，記得回看它是否真的被使用。",
            "放下也很好，清单因此更轻。": "放下也很好，清單因此更輕。",
            "先留在清单里，让预算慢慢清楚。": "先留在清單裡，讓預算慢慢清楚。",
            "想买什么": "想買什麼",
            "先把心动记下来，预算可以慢慢补": "先把心動記下來，預算可以慢慢補",
            "名称": "名稱",
            "可选": "可選",
            "分类": "分類",
            "链接": "連結",
            "商品链接，可选": "商品連結，可選",
            "存钱计划": "存錢計畫",
            "看见一点点靠近，比倒计时更舒服": "看見一點點靠近，比倒數更舒服",
            "标记与备注": "標記與備註",
            "为什么想买？现在担心什么？": "為什麼想買？現在擔心什麼？",
            "先放进清单": "先放進清單",
            "调整这件候物": "調整這件候物",
            "少填几项也没关系，清单会安静地接住它。": "少填幾項也沒關係，清單會安靜地接住它。",
            "标记色": "標記色",
            "无": "無",
            "绿色": "綠色",
            "黄色": "黃色",
            "新增候物": "新增候物",
            "开始使用": "開始使用",
            "欢迎来到候物": "歡迎來到候物",
            "把想买、想存和想放下的东西，先整理成一份轻量清单。": "把想買、想存和想放下的東西，先整理成一份輕量清單。",
            "先记下每个心愿": "先記下每個心願",
            "填写名称、价格、已存金额、分类和链接，让想买变得清楚。": "填寫名稱、價格、已存金額、分類和連結，讓想買變得清楚。",
            "用进度决定节奏": "用進度決定節奏",
            "在详情页继续存入或一键补满，慢慢靠近真正值得拥有的东西。": "在詳情頁繼續存入或一鍵補滿，慢慢靠近真正值得擁有的東西。",
            "轻松整理和备份": "輕鬆整理和備份",
            "搜索、筛选、拖动排序、桌面小组件和 JSON 导出都可以随时使用。": "搜尋、篩選、拖動排序、桌面小工具和 JSON 匯出都可以隨時使用。",
            "微信号已复制": "微信號已複製",
            "更多我的应用": "更多我的應用",
            "给心愿一点等待的形状": "給心願一點等待的形狀",
            "不是购物车，是一页留白。把想买、想存和想放下的东西，慢慢整理到同一张纸上。": "不是購物車，是一頁留白。把想買、想存和想放下的東西，慢慢整理到同一張紙上。",
            "今日先不急着拥有": "今日先不急著擁有"
        ],
        "en": [
            "候物": "AwaitGoods",
            "设置": "Settings",
            "想买": "Wanted",
            "已拥有": "Owned",
            "放下": "Let Go",
            "全部": "All",
            "搜索名称、备注或分类": "Search name, note, or category",
            "排序": "Sort",
            "批量": "Batch",
            "整理清单": "Organize",
            "完成整理": "Done Organizing",
            "先记下心动，给预算一点空间": "Save the wish first. Give the budget room.",
            "清单很轻，今天也很清爽": "The list is light today.",
            "还有 %d 件想买的东西": "%d wanted items",
            "暂无候物": "No wishes yet",
            "慢慢存，轻轻买": "Save slowly, buy lightly",
            "先记下一个心愿": "Save a wish first",
            "价格": "Price",
            "已存": "Saved",
            "标签": "Tag",
            "价格需大于 0": "Price must be greater than 0",
            "已存需大于 0": "Saved amount must be greater than 0",
            "已存不能超过价格": "Saved amount cannot exceed price",
            "已选 %d 件": "%d selected",
            "轻点左侧图标多选": "Tap the left icon to select",
            "可以批量放下、删除或换标记": "Let go, delete, or mark in batch",
            "可以批量放下、移入回收站或换标记": "Let go, move to Trash, or mark in batch",
            "完成": "Done",
            "删除": "Delete",
            "标记": "Mark",
            "删除后不可恢复": "This cannot be undone",
            "移入回收站": "Move to Trash",
            "移入回收站？": "Move to Trash?",
            "删除会先放进回收站": "Deleted wishes go to Trash first",
            "回收站": "Trash",
            "回收站为空": "Trash is empty",
            "暂无已删除候物": "No deleted wishes",
            "恢复": "Restore",
            "彻底删除": "Delete Forever",
            "清空回收站？": "Empty Trash?",
            "确认彻底删除？": "Delete Forever?",
            "这些候物将无法恢复": "These wishes cannot be restored",
            "已放入回收站": "Moved to Trash",
            "已恢复": "Restored",
            "删除选中的候物？": "Delete selected wishes?",
            "取消": "Cancel",
            "手动排序": "Manual",
            "最近添加": "Recent",
            "存钱进度": "Savings",
            "价格高低": "Price",
            "优先级": "Priority",
            "换个标记": "Change mark",
            "编辑": "Edit",
            "复制链接": "Copy link",
            "数码": "Digital",
            "衣物": "Clothing",
            "家居": "Home",
            "书影音": "Books",
            "礼物": "Gift",
            "运动": "Sports",
            "语言": "Language",
            "轻触切换语言": "Tap to switch language",
            "日常偏好": "Preferences",
            "默认值轻一点，记录就不会有负担": "Keep defaults light so logging stays easy",
            "数据": "Data",
            "留一份记录，也可以随时清空": "Keep a copy or clear everything anytime",
            "外观模式": "Appearance",
            "主题配色": "Theme Colors",
            "春日纸笺": "Spring Paper",
            "清爽绿意与纸张质感": "Fresh greens with a paper feel",
            "海盐蓝调": "Sea Salt Blue",
            "蓝绿底色配一点珊瑚": "Blue-green base with coral accents",
            "暮莓花园": "Berry Garden",
            "莓果、鼠尾草和纸白": "Berry, sage, and paper white",
            "墨绿静夜": "Forest Night",
            "深绿与温润木色": "Deep green with warm wood",
            "杏茶暖光": "Apricot Tea",
            "杏色、茶棕和蓝灰": "Apricot, tea brown, and blue gray",
            "小组件展示": "Widget Display",
            "小号 1 件 · 中号 3 件 · 大号 5 件": "Small 1 · Medium 3 · Large 5",
            "生成导出文件": "Create Export File",
            "保存为 JSON 备份": "Save a JSON backup",
            "分享导出文件": "Share Export File",
            "文件已生成，可以发送或存到 iCloud": "File created. Send it or save to iCloud.",
            "清空全部数据": "Clear All Data",
            "会删除所有候物和存钱记录": "Deletes every wish and savings record",
            "联系客服": "Contact Support",
            "有任何问题或建议，欢迎联系我们。": "Questions or ideas are welcome.",
            "微信": "WeChat",
            "已复制": "Copied",
            "点击复制": "Tap to copy",
            "关于 App": "About App",
            "候物 AwaitGoods": "AwaitGoods",
            "v1.0 · 慢慢存，轻轻买": "v1.0 · Save slowly, buy lightly",
            "所有候物都会被删除": "All wishes will be deleted",
            "清空": "Clear",
            "跟随系统": "System",
            "浅色": "Light",
            "深色": "Dark",
            "现在怎么处理": "Next Step",
            "详情": "Details",
            "返回": "Back",
            "存钱": "Savings",
            "目标": "Target",
            "还差": "Left",
            "目标未定": "No target yet",
            "已存满": "Fully saved",
            "记录": "Notes",
            "打开商品页面": "Open Product Page",
            "存入金额": "Deposit amount",
            "存入": "Add",
            "补满": "Fill",
            "已经存满，不需要继续存入": "Already fully saved",
            "存入金额需大于 0": "Deposit must be greater than 0",
            "本次存入不能超过还差金额": "Deposit cannot exceed remaining amount",
            "一点点存起来，心愿会变得更踏实。": "Saving bit by bit makes the wish feel real.",
            "已经拥有，记得回看它是否真的被使用。": "Owned now. Remember to see if it is actually used.",
            "放下也很好，清单因此更轻。": "Letting go is good too. The list gets lighter.",
            "先留在清单里，让预算慢慢清楚。": "Keep it here while the budget gets clearer.",
            "想买什么": "What do you want?",
            "先把心动记下来，预算可以慢慢补": "Save the spark first. The budget can follow.",
            "名称": "Name",
            "比如 AirPods、通勤包": "e.g. AirPods, commute bag",
            "可选": "Optional",
            "分类": "Category",
            "链接": "Link",
            "商品链接，可选": "Product link, optional",
            "存钱计划": "Savings Plan",
            "看见一点点靠近，比倒计时更舒服": "Progress feels better than a countdown",
            "标记与备注": "Mark & Note",
            "为什么想买？现在担心什么？": "Why want it? Any concern now?",
            "新候物": "New Wish",
            "保存": "Save",
            "先放进清单": "Put it on the list",
            "调整这件候物": "Edit this wish",
            "少填几项也没关系，清单会安静地接住它。": "A few fields are enough. The list will hold it.",
            "标记色": "Mark Color",
            "低": "Low",
            "中": "Medium",
            "高": "High",
            "无": "None",
            "绿色": "Green",
            "黄色": "Yellow",
            "粉色": "Pink",
            "灰色": "Gray",
            "新增候物": "Add Wish",
            "开始使用": "Start Using",
            "欢迎来到候物": "Welcome to AwaitGoods",
            "把想买、想存和想放下的东西，先整理成一份轻量清单。": "Turn what you want, what you are saving for, and what you may let go into one light list.",
            "先记下每个心愿": "Save each wish first",
            "填写名称、价格、已存金额、分类和链接，让想买变得清楚。": "Add a name, price, saved amount, category, and link so every wish becomes clear.",
            "用进度决定节奏": "Let progress set the pace",
            "在详情页继续存入或一键补满，慢慢靠近真正值得拥有的东西。": "Keep saving in the detail view or fill the target at once, then move closer to what is truly worth owning.",
            "轻松整理和备份": "Organize and back up lightly",
            "搜索、筛选、拖动排序、桌面小组件和 JSON 导出都可以随时使用。": "Search, filters, drag sorting, home screen widgets, and JSON export are ready whenever you need them.",
            "微信号已复制": "WeChat ID copied",
            "更多我的应用": "More Apps by Me",
            "给心愿一点等待的形状": "Give each wish a shape for waiting",
            "不是购物车，是一页留白。把想买、想存和想放下的东西，慢慢整理到同一张纸上。": "Not a cart, but a quiet page. Gather what you want, what you are saving for, and what you may let go onto the same sheet.",
            "今日先不急着拥有": "No need to own it today"
        ],
        "ja": [
            "候物": "候物",
            "设置": "設定",
            "想买": "欲しい",
            "已拥有": "所有済み",
            "放下": "手放す",
            "全部": "すべて",
            "搜索名称、备注或分类": "名前、メモ、カテゴリを検索",
            "排序": "並び替え",
            "批量": "一括",
            "整理清单": "リスト整理",
            "完成整理": "整理を完了",
            "先记下心动，给预算一点空间": "まず気持ちを残して、予算に余白を。",
            "清单很轻，今天也很清爽": "リストは軽く、今日もすっきり。",
            "还有 %d 件想买的东西": "欲しいものが %d 件あります",
            "暂无候物": "まだ候物はありません",
            "慢慢存，轻轻买": "少しずつ貯めて、軽やかに買う",
            "先记下一个心愿": "まずひとつ残す",
            "价格": "価格",
            "已存": "貯金済み",
            "标签": "タグ",
            "价格需大于 0": "価格は 0 より大きくしてください",
            "已存需大于 0": "貯金額は 0 より大きくしてください",
            "已存不能超过价格": "貯金額は価格を超えられません",
            "已选 %d 件": "%d 件選択中",
            "轻点左侧图标多选": "左のアイコンで複数選択",
            "可以批量放下、删除或换标记": "一括で手放す・削除・印を変更",
            "完成": "完了",
            "删除": "削除",
            "标记": "印",
            "删除后不可恢复": "削除すると元に戻せません",
            "删除选中的候物？": "選択した候物を削除しますか？",
            "取消": "キャンセル",
            "手动排序": "手動順",
            "最近添加": "最近追加",
            "存钱进度": "貯金進捗",
            "价格高低": "価格順",
            "优先级": "優先度",
            "换个标记": "印を変える",
            "编辑": "編集",
            "复制链接": "リンクをコピー",
            "数码": "デジタル",
            "衣物": "服",
            "家居": "暮らし",
            "书影音": "本・映像",
            "礼物": "ギフト",
            "运动": "スポーツ",
            "语言": "言語",
            "轻触切换语言": "タップして言語を切り替え",
            "日常偏好": "日常設定",
            "默认值轻一点，记录就不会有负担": "軽い初期設定で、記録を負担なく",
            "数据": "データ",
            "留一份记录，也可以随时清空": "記録を残して、いつでも整理できます",
            "外观模式": "外観モード",
            "主题配色": "テーマ配色",
            "春日纸笺": "春の便箋",
            "清爽绿意与纸张质感": "爽やかな緑と紙の質感",
            "海盐蓝调": "海塩ブルー",
            "蓝绿底色配一点珊瑚": "青緑に少し珊瑚色",
            "暮莓花园": "夕暮れベリーガーデン",
            "莓果、鼠尾草和纸白": "ベリー、セージ、紙の白",
            "墨绿静夜": "深緑の静夜",
            "深绿与温润木色": "深緑と温かな木色",
            "杏茶暖光": "杏茶の暖かい光",
            "杏色、茶棕和蓝灰": "杏色、茶色、青みグレー",
            "小组件展示": "ウィジェット表示",
            "小号 1 件 · 中号 3 件 · 大号 5 件": "小 1 件・中 3 件・大 5 件",
            "生成导出文件": "書き出しファイルを作成",
            "保存为 JSON 备份": "JSON バックアップとして保存",
            "分享导出文件": "書き出しファイルを共有",
            "文件已生成，可以发送或存到 iCloud": "ファイルを作成しました。送信または iCloud に保存できます。",
            "清空全部数据": "すべてのデータを削除",
            "会删除所有候物和存钱记录": "すべての候物と貯金記録を削除します",
            "联系客服": "サポートに連絡",
            "有任何问题或建议，欢迎联系我们。": "質問や提案があればご連絡ください。",
            "微信": "WeChat",
            "已复制": "コピー済み",
            "点击复制": "タップしてコピー",
            "关于 App": "アプリについて",
            "候物 AwaitGoods": "候物 AwaitGoods",
            "v1.0 · 慢慢存，轻轻买": "v1.0・少しずつ貯めて、軽やかに買う",
            "所有候物都会被删除": "すべての候物が削除されます",
            "清空": "削除",
            "跟随系统": "システム",
            "浅色": "ライト",
            "深色": "ダーク",
            "现在怎么处理": "次にどうする？",
            "详情": "詳細",
            "返回": "戻る",
            "存钱": "貯金",
            "目标": "目標",
            "还差": "残り",
            "目标未定": "目標未設定",
            "已存满": "貯まりました",
            "记录": "記録",
            "打开商品页面": "商品ページを開く",
            "存入金额": "貯金額を入力",
            "存入": "追加",
            "补满": "満額にする",
            "已经存满，不需要继续存入": "すでに満額です",
            "存入金额需大于 0": "追加額は 0 より大きくしてください",
            "本次存入不能超过还差金额": "追加額は残額を超えられません",
            "一点点存起来，心愿会变得更踏实。": "少しずつ貯めると、願いが現実に近づきます。",
            "已经拥有，记得回看它是否真的被使用。": "所有済み。ちゃんと使えているか振り返りましょう。",
            "放下也很好，清单因此更轻。": "手放すのも良い選択。リストが軽くなります。",
            "先留在清单里，让预算慢慢清楚。": "まずリストに置いて、予算をゆっくり見極めましょう。",
            "想买什么": "何が欲しい？",
            "先把心动记下来，预算可以慢慢补": "ときめきを先に残して、予算は少しずつ",
            "名称": "名前",
            "比如 AirPods、通勤包": "例：AirPods、通勤バッグ",
            "可选": "任意",
            "分类": "カテゴリ",
            "链接": "リンク",
            "商品链接，可选": "商品リンク（任意）",
            "存钱计划": "貯金プラン",
            "看见一点点靠近，比倒计时更舒服": "カウントダウンより、近づく感覚を",
            "标记与备注": "印とメモ",
            "为什么想买？现在担心什么？": "なぜ欲しい？今の気がかりは？",
            "新候物": "新しい候物",
            "保存": "保存",
            "先放进清单": "まずリストへ",
            "调整这件候物": "この候物を編集",
            "少填几项也没关系，清单会安静地接住它。": "少しだけでも大丈夫。リストが静かに受け止めます。",
            "标记色": "印の色",
            "低": "低",
            "中": "中",
            "高": "高",
            "无": "なし",
            "绿色": "緑",
            "黄色": "黄",
            "粉色": "ピンク",
            "灰色": "グレー",
            "新增候物": "候物を追加",
            "开始使用": "使い始める",
            "欢迎来到候物": "候物へようこそ",
            "把想买、想存和想放下的东西，先整理成一份轻量清单。": "欲しいもの、貯めたいもの、手放してもよいものを、まず軽いリストに整えます。",
            "先记下每个心愿": "まず願いを記録",
            "填写名称、价格、已存金额、分类和链接，让想买变得清楚。": "名前、価格、貯金額、カテゴリ、リンクを入れて、欲しい理由を見える形にします。",
            "用进度决定节奏": "進捗でペースを決める",
            "在详情页继续存入或一键补满，慢慢靠近真正值得拥有的东西。": "詳細画面で少しずつ貯めたり一括で満額にしたりして、本当に持ちたいものへ近づけます。",
            "轻松整理和备份": "整理とバックアップも軽く",
            "搜索、筛选、拖动排序、桌面小组件和 JSON 导出都可以随时使用。": "検索、絞り込み、ドラッグ並び替え、ホーム画面ウィジェット、JSON 書き出しをいつでも使えます。",
            "微信号已复制": "WeChat ID をコピーしました",
            "更多我的应用": "ほかのアプリを見る",
            "给心愿一点等待的形状": "願いに待つかたちを与える",
            "不是购物车，是一页留白。把想买、想存和想放下的东西，慢慢整理到同一张纸上。": "買い物カートではなく、余白のある一枚。欲しいもの、貯めたいもの、手放してもよいものを、同じ紙の上にゆっくり整えます。",
            "今日先不急着拥有": "今日はまだ所有を急がない"
        ],
        "fr": [
            "候物": "AwaitGoods",
            "设置": "Réglages",
            "想买": "Souhaité",
            "已拥有": "Possédé",
            "放下": "Lâcher",
            "全部": "Tout",
            "搜索名称、备注或分类": "Rechercher nom, note ou catégorie",
            "排序": "Trier",
            "批量": "Lot",
            "整理清单": "Organiser",
            "完成整理": "Terminer",
            "先记下心动，给预算一点空间": "Notez l’envie et laissez respirer le budget.",
            "清单很轻，今天也很清爽": "La liste est légère aujourd’hui.",
            "还有 %d 件想买的东西": "%d envies restantes",
            "暂无候物": "Aucune envie pour le moment",
            "慢慢存，轻轻买": "Épargner doucement, acheter léger",
            "先记下一个心愿": "Noter une envie",
            "价格": "Prix",
            "已存": "Épargné",
            "标签": "Étiquette",
            "价格需大于 0": "Le prix doit être supérieur à 0",
            "已存需大于 0": "Le montant épargné doit être supérieur à 0",
            "已存不能超过价格": "Le montant épargné ne peut pas dépasser le prix",
            "已选 %d 件": "%d sélectionné(s)",
            "轻点左侧图标多选": "Touchez l’icône à gauche pour sélectionner",
            "可以批量放下、删除或换标记": "Lâcher, supprimer ou marquer en lot",
            "完成": "Terminé",
            "删除": "Supprimer",
            "标记": "Marque",
            "删除后不可恢复": "Cette action est irréversible",
            "删除选中的候物？": "Supprimer les envies sélectionnées ?",
            "取消": "Annuler",
            "手动排序": "Manuel",
            "最近添加": "Récent",
            "存钱进度": "Progression",
            "价格高低": "Prix",
            "优先级": "Priorité",
            "换个标记": "Changer la marque",
            "编辑": "Modifier",
            "复制链接": "Copier le lien",
            "数码": "Tech",
            "衣物": "Vêtements",
            "家居": "Maison",
            "书影音": "Livres et médias",
            "礼物": "Cadeau",
            "运动": "Sport",
            "语言": "Langue",
            "轻触切换语言": "Touchez pour changer de langue",
            "日常偏好": "Préférences",
            "默认值轻一点，记录就不会有负担": "Des réglages légers rendent la saisie simple",
            "数据": "Données",
            "留一份记录，也可以随时清空": "Gardez une copie ou effacez tout à tout moment",
            "外观模式": "Apparence",
            "主题配色": "Couleurs du thème",
            "春日纸笺": "Papier de printemps",
            "清爽绿意与纸张质感": "Verts frais et texture papier",
            "海盐蓝调": "Bleu sel de mer",
            "蓝绿底色配一点珊瑚": "Bleu-vert avec une touche corail",
            "暮莓花园": "Jardin de baies",
            "莓果、鼠尾草和纸白": "Baies, sauge et blanc papier",
            "墨绿静夜": "Nuit vert encre",
            "深绿与温润木色": "Vert profond et bois chaleureux",
            "杏茶暖光": "Thé abricot lumineux",
            "杏色、茶棕和蓝灰": "Abricot, brun thé et bleu-gris",
            "小组件展示": "Widgets",
            "小号 1 件 · 中号 3 件 · 大号 5 件": "Petit 1 · Moyen 3 · Grand 5",
            "导入备份文件": "Importer une sauvegarde",
            "从 JSON 恢复或合并候物": "Restaurer ou fusionner depuis JSON",
            "生成导出文件": "Créer un fichier d’export",
            "保存为 JSON 备份": "Enregistrer une sauvegarde JSON",
            "分享导出文件": "Partager l’export",
            "文件已生成，可以发送或存到 iCloud": "Fichier créé. Envoyez-le ou enregistrez-le dans iCloud.",
            "备份文件已导入": "Sauvegarde importée",
            "新增 %d 条 · 更新 %d 条": "%d ajouté(s) · %d mis à jour",
            "无法导入备份文件": "Impossible d’importer la sauvegarde",
            "请确认选择的是候物导出的 JSON 文件": "Choisissez un fichier JSON exporté par AwaitGoods",
            "备份文件里没有可导入的候物": "Aucune envie importable dans cette sauvegarde",
            "清空全部数据": "Effacer toutes les données",
            "会删除所有候物和存钱记录": "Supprime toutes les envies et l’épargne",
            "联系客服": "Contacter le support",
            "有任何问题或建议，欢迎联系我们。": "Questions et idées sont les bienvenues.",
            "微信": "WeChat",
            "已复制": "Copié",
            "点击复制": "Toucher pour copier",
            "微信号已复制": "ID WeChat copié",
            "更多我的应用": "Mes autres apps",
            "关于 App": "À propos",
            "候物 AwaitGoods": "AwaitGoods",
            "所有候物都会被删除": "Toutes les envies seront supprimées",
            "清空": "Effacer",
            "跟随系统": "Système",
            "浅色": "Clair",
            "深色": "Sombre",
            "现在怎么处理": "Étape suivante",
            "详情": "Détails",
            "返回": "Retour",
            "存钱": "Épargne",
            "目标": "Objectif",
            "还差": "Restant",
            "目标未定": "Objectif non défini",
            "已存满": "Objectif atteint",
            "记录": "Notes",
            "打开商品页面": "Ouvrir la page produit",
            "存入金额": "Montant à ajouter",
            "存入": "Ajouter",
            "补满": "Compléter",
            "已经存满，不需要继续存入": "Objectif déjà atteint",
            "存入金额需大于 0": "Le montant doit être supérieur à 0",
            "本次存入不能超过还差金额": "Le montant ne peut pas dépasser le reste",
            "一点点存起来，心愿会变得更踏实。": "Petit à petit, l’envie devient plus concrète.",
            "已经拥有，记得回看它是否真的被使用。": "Déjà possédé. Pensez à vérifier s’il sert vraiment.",
            "放下也很好，清单因此更轻。": "Lâcher prise allège aussi la liste.",
            "先留在清单里，让预算慢慢清楚。": "Gardez-le ici pendant que le budget se clarifie.",
            "想买什么": "Que voulez-vous ?",
            "先把心动记下来，预算可以慢慢补": "Notez l’envie d’abord. Le budget suivra.",
            "名称": "Nom",
            "比如 AirPods、通勤包": "Ex. AirPods, sac de trajet",
            "可选": "Optionnel",
            "分类": "Catégorie",
            "链接": "Lien",
            "商品链接，可选": "Lien produit, optionnel",
            "存钱计划": "Plan d’épargne",
            "看见一点点靠近，比倒计时更舒服": "Voir la progression est plus doux qu’un compte à rebours",
            "标记与备注": "Marque et note",
            "为什么想买？现在担心什么？": "Pourquoi le vouloir ? Une hésitation ?",
            "新候物": "Nouvelle envie",
            "保存": "Enregistrer",
            "先放进清单": "Ajouter à la liste",
            "调整这件候物": "Modifier cette envie",
            "少填几项也没关系，清单会安静地接住它。": "Quelques champs suffisent. La liste l’accueille.",
            "标记色": "Couleur",
            "低": "Basse",
            "中": "Moyenne",
            "高": "Haute",
            "无": "Aucune",
            "绿色": "Vert",
            "黄色": "Jaune",
            "粉色": "Rose",
            "灰色": "Gris",
            "新增候物": "Ajouter une envie",
            "开始使用": "Commencer",
            "先记下每个心愿": "Noter chaque envie",
            "填写名称、价格、已存金额、分类和链接，让想买变得清楚。": "Ajoutez nom, prix, épargne, catégorie et lien pour clarifier l’envie.",
            "用进度决定节奏": "Laisser la progression guider le rythme",
            "在详情页继续存入或一键补满，慢慢靠近真正值得拥有的东西。": "Ajoutez de l’épargne ou complétez l’objectif pour avancer vers ce qui vaut vraiment la peine.",
            "轻松整理和备份": "Organiser et sauvegarder simplement",
            "搜索、筛选、拖动排序、桌面小组件和 JSON 导出都可以随时使用。": "Recherche, filtres, tri manuel, widgets et export JSON restent toujours prêts.",
            "给心愿一点等待的形状": "Donner une forme à l’attente",
            "不是购物车，是一页留白。把想买、想存和想放下的东西，慢慢整理到同一张纸上。": "Pas un panier, mais une page calme. Rassemblez envies, épargne et choses à lâcher sur la même feuille.",
            "今日先不急着拥有": "Pas besoin de posséder aujourd’hui"
        ],
        "de": [
            "候物": "AwaitGoods",
            "设置": "Einstellungen",
            "想买": "Gewünscht",
            "已拥有": "Besitzt",
            "放下": "Loslassen",
            "全部": "Alle",
            "搜索名称、备注或分类": "Name, Notiz oder Kategorie suchen",
            "排序": "Sortieren",
            "批量": "Stapel",
            "整理清单": "Organisieren",
            "完成整理": "Fertig",
            "先记下心动，给预算一点空间": "Erst notieren, dem Budget Raum geben.",
            "清单很轻，今天也很清爽": "Die Liste ist heute leicht.",
            "还有 %d 件想买的东西": "%d gewünschte Dinge",
            "暂无候物": "Noch keine Wünsche",
            "慢慢存，轻轻买": "Langsam sparen, leicht kaufen",
            "先记下一个心愿": "Einen Wunsch notieren",
            "价格": "Preis",
            "已存": "Gespart",
            "标签": "Tag",
            "价格需大于 0": "Der Preis muss größer als 0 sein",
            "已存需大于 0": "Der gesparte Betrag muss größer als 0 sein",
            "已存不能超过价格": "Der gesparte Betrag darf den Preis nicht überschreiten",
            "已选 %d 件": "%d ausgewählt",
            "轻点左侧图标多选": "Links antippen, um auszuwählen",
            "可以批量放下、删除或换标记": "Loslassen, löschen oder markieren",
            "完成": "Fertig",
            "删除": "Löschen",
            "标记": "Markieren",
            "删除后不可恢复": "Das kann nicht rückgängig gemacht werden",
            "删除选中的候物？": "Ausgewählte Wünsche löschen?",
            "取消": "Abbrechen",
            "手动排序": "Manuell",
            "最近添加": "Neueste",
            "存钱进度": "Sparen",
            "价格高低": "Preis",
            "优先级": "Priorität",
            "换个标记": "Markierung ändern",
            "编辑": "Bearbeiten",
            "复制链接": "Link kopieren",
            "数码": "Technik",
            "衣物": "Kleidung",
            "家居": "Zuhause",
            "书影音": "Bücher und Medien",
            "礼物": "Geschenk",
            "运动": "Sport",
            "语言": "Sprache",
            "轻触切换语言": "Tippen, um die Sprache zu wechseln",
            "日常偏好": "Präferenzen",
            "默认值轻一点，记录就不会有负担": "Leichte Vorgaben machen das Erfassen einfach",
            "数据": "Daten",
            "留一份记录，也可以随时清空": "Kopie behalten oder jederzeit löschen",
            "外观模式": "Darstellung",
            "主题配色": "Farbthema",
            "春日纸笺": "Frühlingspapier",
            "清爽绿意与纸张质感": "Frisches Grün mit Papiergefühl",
            "海盐蓝调": "Meersalz-Blau",
            "蓝绿底色配一点珊瑚": "Blaugrün mit Korallenakzent",
            "暮莓花园": "Beerengarten",
            "莓果、鼠尾草和纸白": "Beeren, Salbei und Papierweiß",
            "墨绿静夜": "Tiefgrüne Nacht",
            "深绿与温润木色": "Tiefgrün mit warmem Holz",
            "杏茶暖光": "Aprikosentee-Licht",
            "杏色、茶棕和蓝灰": "Aprikose, Teebraun und Blaugrau",
            "小组件展示": "Widgets",
            "小号 1 件 · 中号 3 件 · 大号 5 件": "Klein 1 · Mittel 3 · Groß 5",
            "导入备份文件": "Backup importieren",
            "从 JSON 恢复或合并候物": "Aus JSON wiederherstellen oder zusammenführen",
            "生成导出文件": "Exportdatei erstellen",
            "保存为 JSON 备份": "Als JSON-Backup speichern",
            "分享导出文件": "Export teilen",
            "文件已生成，可以发送或存到 iCloud": "Datei erstellt. Senden oder in iCloud speichern.",
            "备份文件已导入": "Backup importiert",
            "新增 %d 条 · 更新 %d 条": "%d hinzugefügt · %d aktualisiert",
            "无法导入备份文件": "Backup kann nicht importiert werden",
            "请确认选择的是候物导出的 JSON 文件": "Bitte eine von AwaitGoods exportierte JSON-Datei wählen",
            "备份文件里没有可导入的候物": "Keine importierbaren Wünsche im Backup",
            "清空全部数据": "Alle Daten löschen",
            "会删除所有候物和存钱记录": "Löscht alle Wünsche und Sparstände",
            "联系客服": "Support kontaktieren",
            "有任何问题或建议，欢迎联系我们。": "Fragen und Ideen sind willkommen.",
            "微信": "WeChat",
            "已复制": "Kopiert",
            "点击复制": "Zum Kopieren tippen",
            "微信号已复制": "WeChat-ID kopiert",
            "更多我的应用": "Weitere Apps von mir",
            "关于 App": "Über die App",
            "候物 AwaitGoods": "AwaitGoods",
            "所有候物都会被删除": "Alle Wünsche werden gelöscht",
            "清空": "Löschen",
            "跟随系统": "System",
            "浅色": "Hell",
            "深色": "Dunkel",
            "现在怎么处理": "Nächster Schritt",
            "详情": "Details",
            "返回": "Zurück",
            "存钱": "Sparen",
            "目标": "Ziel",
            "还差": "Übrig",
            "目标未定": "Kein Ziel",
            "已存满": "Voll gespart",
            "记录": "Notizen",
            "打开商品页面": "Produktseite öffnen",
            "存入金额": "Betrag einzahlen",
            "存入": "Hinzufügen",
            "补满": "Auffüllen",
            "已经存满，不需要继续存入": "Bereits voll gespart",
            "存入金额需大于 0": "Der Betrag muss größer als 0 sein",
            "本次存入不能超过还差金额": "Der Betrag darf den Rest nicht überschreiten",
            "一点点存起来，心愿会变得更踏实。": "Schritt für Schritt wird der Wunsch greifbarer.",
            "已经拥有，记得回看它是否真的被使用。": "Schon besitzt. Später prüfen, ob es wirklich genutzt wird.",
            "放下也很好，清单因此更轻。": "Loslassen macht die Liste leichter.",
            "先留在清单里，让预算慢慢清楚。": "Hier behalten, während das Budget klarer wird.",
            "想买什么": "Was möchten Sie?",
            "先把心动记下来，预算可以慢慢补": "Erst notieren. Das Budget kann folgen.",
            "名称": "Name",
            "比如 AirPods、通勤包": "z. B. AirPods, Pendeltasche",
            "可选": "Optional",
            "分类": "Kategorie",
            "链接": "Link",
            "商品链接，可选": "Produktlink, optional",
            "存钱计划": "Sparplan",
            "看见一点点靠近，比倒计时更舒服": "Fortschritt fühlt sich besser an als ein Countdown",
            "标记与备注": "Markierung und Notiz",
            "为什么想买？现在担心什么？": "Warum wollen Sie es? Gibt es Bedenken?",
            "新候物": "Neuer Wunsch",
            "保存": "Speichern",
            "先放进清单": "Zur Liste hinzufügen",
            "调整这件候物": "Diesen Wunsch bearbeiten",
            "少填几项也没关系，清单会安静地接住它。": "Ein paar Felder reichen. Die Liste hält es fest.",
            "标记色": "Farbe",
            "低": "Niedrig",
            "中": "Mittel",
            "高": "Hoch",
            "无": "Keine",
            "绿色": "Grün",
            "黄色": "Gelb",
            "粉色": "Rosa",
            "灰色": "Grau",
            "新增候物": "Wunsch hinzufügen",
            "开始使用": "Loslegen",
            "先记下每个心愿": "Jeden Wunsch zuerst notieren",
            "填写名称、价格、已存金额、分类和链接，让想买变得清楚。": "Name, Preis, Sparbetrag, Kategorie und Link machen den Wunsch klar.",
            "用进度决定节奏": "Den Rhythmus am Fortschritt ausrichten",
            "在详情页继续存入或一键补满，慢慢靠近真正值得拥有的东西。": "Im Detail weiter sparen oder auffüllen und dem wirklich Wertvollen näherkommen.",
            "轻松整理和备份": "Einfach organisieren und sichern",
            "搜索、筛选、拖动排序、桌面小组件和 JSON 导出都可以随时使用。": "Suche, Filter, Ziehsortierung, Widgets und JSON-Export sind jederzeit bereit.",
            "给心愿一点等待的形状": "Dem Warten eine Form geben",
            "不是购物车，是一页留白。把想买、想存和想放下的东西，慢慢整理到同一张纸上。": "Kein Warenkorb, sondern eine ruhige Seite. Wünsche, Sparziele und Losgelassenes finden auf demselben Blatt Platz.",
            "今日先不急着拥有": "Heute muss es nicht sofort Ihnen gehören"
        ],
        "it": [
            "候物": "AwaitGoods",
            "设置": "Impostazioni",
            "想买": "Desideri",
            "已拥有": "Posseduto",
            "放下": "Lasciare",
            "全部": "Tutto",
            "搜索名称、备注或分类": "Cerca nome, nota o categoria",
            "排序": "Ordina",
            "批量": "Azioni",
            "整理清单": "Organizza",
            "完成整理": "Fine",
            "先记下心动，给预算一点空间": "Salva il desiderio e lascia spazio al budget.",
            "清单很轻，今天也很清爽": "La lista oggi è leggera.",
            "还有 %d 件想买的东西": "%d desideri rimasti",
            "暂无候物": "Ancora nessun desiderio",
            "慢慢存，轻轻买": "Risparmia piano, compra leggero",
            "先记下一个心愿": "Salva un desiderio",
            "价格": "Prezzo",
            "已存": "Risparmiato",
            "标签": "Etichetta",
            "价格需大于 0": "Il prezzo deve essere maggiore di 0",
            "已存需大于 0": "Il risparmio deve essere maggiore di 0",
            "已存不能超过价格": "Il risparmio non può superare il prezzo",
            "已选 %d 件": "%d selezionati",
            "轻点左侧图标多选": "Tocca l’icona a sinistra per selezionare",
            "可以批量放下、删除或换标记": "Lascia, elimina o marca in gruppo",
            "完成": "Fine",
            "删除": "Elimina",
            "标记": "Marca",
            "删除后不可恢复": "L’azione non può essere annullata",
            "删除选中的候物？": "Eliminare i desideri selezionati?",
            "取消": "Annulla",
            "手动排序": "Manuale",
            "最近添加": "Recenti",
            "存钱进度": "Risparmio",
            "价格高低": "Prezzo",
            "优先级": "Priorità",
            "换个标记": "Cambia marca",
            "编辑": "Modifica",
            "复制链接": "Copia link",
            "数码": "Tech",
            "衣物": "Abbigliamento",
            "家居": "Casa",
            "书影音": "Libri e media",
            "礼物": "Regalo",
            "运动": "Sport",
            "语言": "Lingua",
            "轻触切换语言": "Tocca per cambiare lingua",
            "日常偏好": "Preferenze",
            "默认值轻一点，记录就不会有负担": "Valori leggeri rendono la registrazione semplice",
            "数据": "Dati",
            "留一份记录，也可以随时清空": "Conserva una copia o cancella tutto quando vuoi",
            "外观模式": "Aspetto",
            "主题配色": "Colori tema",
            "春日纸笺": "Carta di primavera",
            "清爽绿意与纸张质感": "Verdi freschi e texture carta",
            "海盐蓝调": "Blu sale marino",
            "蓝绿底色配一点珊瑚": "Base blu-verde con corallo",
            "暮莓花园": "Giardino di bacche",
            "莓果、鼠尾草和纸白": "Bacche, salvia e bianco carta",
            "墨绿静夜": "Notte verde inchiostro",
            "深绿与温润木色": "Verde profondo e legno caldo",
            "杏茶暖光": "Luce tè albicocca",
            "杏色、茶棕和蓝灰": "Albicocca, tè marrone e blu-grigio",
            "小组件展示": "Widget",
            "小号 1 件 · 中号 3 件 · 大号 5 件": "Piccolo 1 · Medio 3 · Grande 5",
            "导入备份文件": "Importa backup",
            "从 JSON 恢复或合并候物": "Ripristina o unisci da JSON",
            "生成导出文件": "Crea file di esportazione",
            "保存为 JSON 备份": "Salva backup JSON",
            "分享导出文件": "Condividi esportazione",
            "文件已生成，可以发送或存到 iCloud": "File creato. Invialo o salvalo su iCloud.",
            "备份文件已导入": "Backup importato",
            "新增 %d 条 · 更新 %d 条": "%d aggiunti · %d aggiornati",
            "无法导入备份文件": "Impossibile importare il backup",
            "请确认选择的是候物导出的 JSON 文件": "Scegli un JSON esportato da AwaitGoods",
            "备份文件里没有可导入的候物": "Nessun desiderio importabile nel backup",
            "清空全部数据": "Cancella tutti i dati",
            "会删除所有候物和存钱记录": "Elimina tutti i desideri e i risparmi",
            "联系客服": "Contatta il supporto",
            "有任何问题或建议，欢迎联系我们。": "Domande e idee sono benvenute.",
            "微信": "WeChat",
            "已复制": "Copiato",
            "点击复制": "Tocca per copiare",
            "微信号已复制": "ID WeChat copiato",
            "更多我的应用": "Altre mie app",
            "关于 App": "Info app",
            "候物 AwaitGoods": "AwaitGoods",
            "所有候物都会被删除": "Tutti i desideri saranno eliminati",
            "清空": "Cancella",
            "跟随系统": "Sistema",
            "浅色": "Chiaro",
            "深色": "Scuro",
            "现在怎么处理": "Prossimo passo",
            "详情": "Dettagli",
            "返回": "Indietro",
            "存钱": "Risparmio",
            "目标": "Obiettivo",
            "还差": "Manca",
            "目标未定": "Nessun obiettivo",
            "已存满": "Completato",
            "记录": "Note",
            "打开商品页面": "Apri pagina prodotto",
            "存入金额": "Importo da aggiungere",
            "存入": "Aggiungi",
            "补满": "Completa",
            "已经存满，不需要继续存入": "Obiettivo già completato",
            "存入金额需大于 0": "L’importo deve essere maggiore di 0",
            "本次存入不能超过还差金额": "L’importo non può superare il residuo",
            "一点点存起来，心愿会变得更踏实。": "Poco a poco, il desiderio diventa concreto.",
            "已经拥有，记得回看它是否真的被使用。": "Già posseduto. Verifica se lo usi davvero.",
            "放下也很好，清单因此更轻。": "Lasciare andare alleggerisce la lista.",
            "先留在清单里，让预算慢慢清楚。": "Tienilo qui mentre il budget diventa chiaro.",
            "想买什么": "Cosa desideri?",
            "先把心动记下来，预算可以慢慢补": "Salva prima l’idea. Il budget può seguire.",
            "名称": "Nome",
            "比如 AirPods、通勤包": "es. AirPods, borsa da lavoro",
            "可选": "Opzionale",
            "分类": "Categoria",
            "链接": "Link",
            "商品链接，可选": "Link prodotto, opzionale",
            "存钱计划": "Piano di risparmio",
            "看见一点点靠近，比倒计时更舒服": "Vedere il progresso è meglio di un conto alla rovescia",
            "标记与备注": "Marca e nota",
            "为什么想买？现在担心什么？": "Perché lo vuoi? Hai dubbi?",
            "新候物": "Nuovo desiderio",
            "保存": "Salva",
            "先放进清单": "Aggiungi alla lista",
            "调整这件候物": "Modifica desiderio",
            "少填几项也没关系，清单会安静地接住它。": "Bastano pochi campi. La lista lo accoglie.",
            "标记色": "Colore",
            "低": "Bassa",
            "中": "Media",
            "高": "Alta",
            "无": "Nessuno",
            "绿色": "Verde",
            "黄色": "Giallo",
            "粉色": "Rosa",
            "灰色": "Grigio",
            "新增候物": "Aggiungi desiderio",
            "开始使用": "Inizia",
            "先记下每个心愿": "Salva prima ogni desiderio",
            "填写名称、价格、已存金额、分类和链接，让想买变得清楚。": "Nome, prezzo, risparmio, categoria e link rendono chiaro il desiderio.",
            "用进度决定节奏": "Lascia che il progresso dia il ritmo",
            "在详情页继续存入或一键补满，慢慢靠近真正值得拥有的东西。": "Aggiungi risparmi o completa l’obiettivo per avvicinarti a ciò che vale davvero.",
            "轻松整理和备份": "Organizza e salva con leggerezza",
            "搜索、筛选、拖动排序、桌面小组件和 JSON 导出都可以随时使用。": "Ricerca, filtri, ordinamento, widget ed export JSON sono sempre pronti.",
            "给心愿一点等待的形状": "Dai una forma all’attesa",
            "不是购物车，是一页留白。把想买、想存和想放下的东西，慢慢整理到同一张纸上。": "Non un carrello, ma una pagina calma. Desideri, risparmi e cose da lasciare trovano posto sullo stesso foglio.",
            "今日先不急着拥有": "Oggi non serve possederlo subito"
        ],
        "ko": [
            "候物": "AwaitGoods",
            "设置": "설정",
            "想买": "사고 싶음",
            "已拥有": "보유함",
            "放下": "내려놓음",
            "全部": "전체",
            "搜索名称、备注或分类": "이름, 메모 또는 분류 검색",
            "排序": "정렬",
            "批量": "일괄",
            "整理清单": "목록 정리",
            "完成整理": "완료",
            "先记下心动，给预算一点空间": "먼저 적어 두고 예산에 여백을 주세요.",
            "清单很轻，今天也很清爽": "오늘 목록은 가볍습니다.",
            "还有 %d 件想买的东西": "사고 싶은 항목 %d개",
            "暂无候物": "아직 항목이 없습니다",
            "慢慢存，轻轻买": "천천히 모으고 가볍게 사기",
            "先记下一个心愿": "먼저 하나 적어 두기",
            "价格": "가격",
            "已存": "모은 금액",
            "标签": "태그",
            "价格需大于 0": "가격은 0보다 커야 합니다",
            "已存需大于 0": "모은 금액은 0보다 커야 합니다",
            "已存不能超过价格": "모은 금액은 가격을 넘을 수 없습니다",
            "已选 %d 件": "%d개 선택됨",
            "轻点左侧图标多选": "왼쪽 아이콘을 눌러 선택하세요",
            "可以批量放下、删除或换标记": "일괄 내려놓기, 삭제 또는 표시 변경",
            "完成": "완료",
            "删除": "삭제",
            "标记": "표시",
            "删除后不可恢复": "삭제하면 되돌릴 수 없습니다",
            "删除选中的候物？": "선택한 항목을 삭제할까요?",
            "取消": "취소",
            "手动排序": "수동",
            "最近添加": "최근 추가",
            "存钱进度": "저축 진행",
            "价格高低": "가격",
            "优先级": "우선순위",
            "换个标记": "표시 변경",
            "编辑": "편집",
            "复制链接": "링크 복사",
            "数码": "디지털",
            "衣物": "의류",
            "家居": "생활",
            "书影音": "책과 미디어",
            "礼物": "선물",
            "运动": "운동",
            "语言": "언어",
            "轻触切换语言": "눌러서 언어 전환",
            "日常偏好": "기본 설정",
            "默认值轻一点，记录就不会有负担": "가벼운 기본값으로 부담 없이 기록하세요",
            "数据": "데이터",
            "留一份记录，也可以随时清空": "기록을 남기거나 언제든 비울 수 있습니다",
            "外观模式": "화면 모드",
            "主题配色": "테마 색상",
            "春日纸笺": "봄날 종이",
            "清爽绿意与纸张质感": "맑은 초록과 종이 질감",
            "海盐蓝调": "바다소금 블루",
            "蓝绿底色配一点珊瑚": "블루그린에 산호빛 한 점",
            "暮莓花园": "저녁 베리 정원",
            "莓果、鼠尾草和纸白": "베리, 세이지, 종이 흰색",
            "墨绿静夜": "먹빛 초록 밤",
            "深绿与温润木色": "깊은 초록과 따뜻한 나무색",
            "杏茶暖光": "살구차의 따뜻한 빛",
            "杏色、茶棕和蓝灰": "살구색, 차 브라운, 블루 그레이",
            "小组件展示": "위젯 표시",
            "小号 1 件 · 中号 3 件 · 大号 5 件": "소형 1개 · 중형 3개 · 대형 5개",
            "导入备份文件": "백업 파일 가져오기",
            "从 JSON 恢复或合并候物": "JSON에서 복원 또는 병합",
            "生成导出文件": "내보내기 파일 만들기",
            "保存为 JSON 备份": "JSON 백업으로 저장",
            "分享导出文件": "내보내기 파일 공유",
            "文件已生成，可以发送或存到 iCloud": "파일이 생성되었습니다. 보내거나 iCloud에 저장하세요.",
            "备份文件已导入": "백업 파일을 가져왔습니다",
            "新增 %d 条 · 更新 %d 条": "%d개 추가 · %d개 업데이트",
            "无法导入备份文件": "백업 파일을 가져올 수 없습니다",
            "请确认选择的是候物导出的 JSON 文件": "AwaitGoods에서 내보낸 JSON 파일인지 확인하세요",
            "备份文件里没有可导入的候物": "가져올 항목이 백업에 없습니다",
            "清空全部数据": "모든 데이터 지우기",
            "会删除所有候物和存钱记录": "모든 항목과 저축 기록을 삭제합니다",
            "联系客服": "지원 문의",
            "有任何问题或建议，欢迎联系我们。": "질문이나 제안을 보내 주세요.",
            "微信": "WeChat",
            "已复制": "복사됨",
            "点击复制": "눌러서 복사",
            "微信号已复制": "WeChat ID가 복사되었습니다",
            "更多我的应用": "내 다른 앱 더 보기",
            "关于 App": "앱 정보",
            "候物 AwaitGoods": "AwaitGoods",
            "所有候物都会被删除": "모든 항목이 삭제됩니다",
            "清空": "지우기",
            "跟随系统": "시스템",
            "浅色": "라이트",
            "深色": "다크",
            "现在怎么处理": "다음 단계",
            "详情": "상세",
            "返回": "뒤로",
            "存钱": "저축",
            "目标": "목표",
            "还差": "남음",
            "目标未定": "목표 없음",
            "已存满": "저축 완료",
            "记录": "메모",
            "打开商品页面": "상품 페이지 열기",
            "存入金额": "저축할 금액",
            "存入": "추가",
            "补满": "채우기",
            "已经存满，不需要继续存入": "이미 목표를 채웠습니다",
            "存入金额需大于 0": "금액은 0보다 커야 합니다",
            "本次存入不能超过还差金额": "남은 금액을 넘을 수 없습니다",
            "一点点存起来，心愿会变得更踏实。": "조금씩 모으면 마음이 더 단단해집니다.",
            "已经拥有，记得回看它是否真的被使用。": "이미 가지고 있다면 실제로 쓰는지 돌아보세요.",
            "放下也很好，清单因此更轻。": "내려놓는 것도 좋은 선택입니다. 목록이 가벼워집니다.",
            "先留在清单里，让预算慢慢清楚。": "우선 목록에 두고 예산을 천천히 정리하세요.",
            "想买什么": "무엇을 사고 싶나요?",
            "先把心动记下来，预算可以慢慢补": "먼저 적어 두세요. 예산은 천천히 따라오면 됩니다.",
            "名称": "이름",
            "比如 AirPods、通勤包": "예: AirPods, 출근 가방",
            "可选": "선택 사항",
            "分类": "분류",
            "链接": "링크",
            "商品链接，可选": "상품 링크, 선택 사항",
            "存钱计划": "저축 계획",
            "看见一点点靠近，比倒计时更舒服": "카운트다운보다 가까워지는 느낌이 좋습니다",
            "标记与备注": "표시와 메모",
            "为什么想买？现在担心什么？": "왜 사고 싶나요? 걱정되는 점은요?",
            "新候物": "새 항목",
            "保存": "저장",
            "先放进清单": "목록에 넣기",
            "调整这件候物": "이 항목 수정",
            "少填几项也没关系，清单会安静地接住它。": "몇 가지만 적어도 괜찮습니다. 목록이 조용히 받아 줍니다.",
            "标记色": "표시 색",
            "低": "낮음",
            "中": "중간",
            "高": "높음",
            "无": "없음",
            "绿色": "초록",
            "黄色": "노랑",
            "粉色": "분홍",
            "灰色": "회색",
            "新增候物": "항목 추가",
            "开始使用": "시작하기",
            "先记下每个心愿": "각 마음을 먼저 적어 두기",
            "填写名称、价格、已存金额、分类和链接，让想买变得清楚。": "이름, 가격, 저축액, 분류와 링크를 적어 마음을 선명하게 만드세요.",
            "用进度决定节奏": "진행률로 속도를 정하기",
            "在详情页继续存入或一键补满，慢慢靠近真正值得拥有的东西。": "상세 화면에서 더 모으거나 한 번에 채워 정말 가질 만한 것에 가까워지세요.",
            "轻松整理和备份": "가볍게 정리하고 백업하기",
            "搜索、筛选、拖动排序、桌面小组件和 JSON 导出都可以随时使用。": "검색, 필터, 드래그 정렬, 홈 화면 위젯과 JSON 내보내기를 언제든 사용할 수 있습니다.",
            "给心愿一点等待的形状": "기다림에 모양을 주기",
            "不是购物车，是一页留白。把想买、想存和想放下的东西，慢慢整理到同一张纸上。": "장바구니가 아니라 여백 있는 한 장입니다. 사고 싶은 것, 모으는 것, 내려놓을 것을 같은 종이에 천천히 정리하세요.",
            "今日先不急着拥有": "오늘은 서두르지 않아도 됩니다"
        ]
    ]
}

private struct AppLanguageKey: EnvironmentKey {
    static let defaultValue: AppLanguage = .zhHans
}

extension EnvironmentValues {
    var appLanguage: AppLanguage {
        get { self[AppLanguageKey.self] }
        set { self[AppLanguageKey.self] = newValue }
    }
}
